<?php

return [
    'form_type' => [
        'formal' => [
            [
                'title' => 'Nava Dhammasekha',
                'code' => 'nava-dhammasekha',
                'codex' => 'FL-NVDMSK',
                'file_count' => 0, 
                'description' => 'Pendidikan dasar keagamaan Buddha setingkat sekolah dasar. Persyaratan lengkap mencakup akta notaris, kurikulum, daftar guru, hingga studi kelayakan.',
                'fields' => [
                    [
                        'type' => 'text',
                        'name' => 'pic_name',
                        'label' => 'Nama Penanggung Jawab',
                        'placeholder' => 'Input nama penanggung jawab',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'identitas-lembaga',
                        'group' => 1,
                    ],
                    [
                        'type' => 'text',
                        'name' => 'institution_name',
                        'label' => 'Nama Lembaga Pendidikan',
                        'placeholder' => 'Masukkan nama lembaga pendidikan',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'identitas-lembaga',
                        'group' => 1,
                    ],
                    [
                        'type' => 'text',
                        'name' => 'institution_head_name',
                        'label' => 'Nama Kepala Lembaga',
                        'placeholder' => 'Masukkan nama kepala lembaga pendidikan',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'identitas-lembaga',
                        'group' => 1,
                    ],
                    [
                        'type' => 'text',
                        'name' => 'organizing_body_name',
                        'label' => 'Nama Badan Penyelenggara',
                        'placeholder' => 'Masukkan nama badan penyelenggara',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'identitas-lembaga',
                        'group' => 2,
                    ],
                    
                    [
                        'type' => 'text',
                        'name' => 'institution_phone',
                        'label' => 'Nomor Telepon Lembaga',
                        'placeholder' => 'Masukkan nomor telpon lembaga pendidikan',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'identitas-lembaga',
                        'group' => 2,
                    ],
                    [
                        'type' => 'date',
                        'name' => 'established_date',
                        'label' => 'Tanggal Berdiri',
                        'placeholder' => 'Pilih tanggal',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'identitas-lembaga',
                        'group' => 2,
                    ],
                    // dok
                    [
                        'type' => 'file',
                        'name' => 'docs_1',
                        'label' => 'Tanda Daftar Yayasan/Perkumpulan dari Kementerian Agama',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'dokumen-penyelenggara',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'docs_2',
                        'label' => 'AD/ART ',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'dokumen-penyelenggara',
                    ],
                    [
                        'type' => 'custom_address',
                        'name' => 'province',
                        'label' => 'Provinsi',
                        'placeholder' => 'Pilih Provinsi',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'alamat-lembaga-pendidikan',
                        'group' => 1,
                    ],
                    [
                        'type' => 'custom_address',
                        'name' => 'city',
                        'label' => 'Kabupaten',
                        'placeholder' => 'Pilih Kabupaten',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'alamat-lembaga-pendidikan',
                        'group' => 2,
                    ],
                    [
                        'type' => 'custom_address',
                        'name' => 'district',
                        'label' => 'Kecamatan',
                        'placeholder' => 'Pilih Kabupaten',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'alamat-lembaga-pendidikan',
                        'group' => 1,
                    ],
                    [
                        'type' => 'custom_address',
                        'name' => 'subdistrict',
                        'label' => 'Kelurahan',
                        'placeholder' => 'Pilih Kecamatan',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'alamat-lembaga-pendidikan',
                        'group' => 2,
                    ],
                    [
                        'type' => 'textarea',
                        'name' => 'address',
                        'label' => 'Alamat Lengkap',
                        'placeholder' => 'Masukkan alamat lembaga',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'alamat-lembaga-pendidikan',
                        'group' => 1
                    ],
                    [
                        'type' => 'file',
                        'name' => 'photo_1',
                        'label' => 'Foto Sarpras',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'sarana-&-Foto',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'photo_2',
                        'label' => 'Foto Gedung Depan',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'sarana-&-Foto',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'photo_3',
                        'label' => 'Foto Gedung Samping',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'sarana-&-Foto',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'photo_4',
                        'label' => 'Tambahan Foto Sarpras',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'sarana-&-Foto',
                    ],

                    // Rekening
                    [
                        'type' => 'select',
                        'name' => 'bank_name',
                        'label' => 'Pilih Bank',
                        'placeholder' => 'Pilih Bank',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'rekening',
                        'group' => 1,
                        'options' => [
                            'BCA|Bank Central Asia (BCA)',
                            'BRI|Bank Rakyat Indonesia (BRI',
                            'BNI|Bank Negara Indonesia (BNI)',
                            'BTN|Bank Tabungan Negara (BTN)',
                        ]
                    ],
                    [
                        'type' => 'text',
                        'name' => 'bank_account',
                        'label' => 'Nomor Rekening',
                        'placeholder' => 'Nomor Rekening',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'rekening',
                        'group' => 1,
                    ],
                    [
                        'type' => 'text',
                        'name' => 'bank_office',
                        'label' => 'Cabang Bank',
                        'placeholder' => 'Cabang Bank',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'rekening',
                        'group' => 1,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'docs_3',
                        'label' => 'Upload Foto Rekening',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'rekening',
                    ],
                    // PAGE 2
                    [
                        'type' => 'file',
                        'name' => 'docs_4',
                        'label' => 'SK Pengurus Organisasi (struktur & susunan + KTP)',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'docs_5',
                        'label' => 'SK Struktur Manajemen & Personalia Penyelenggara Pendidikan',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'docs_6',
                        'label' => 'Surat Pernyataan Kesanggupan Pembiayaan min. 1 tahun (bermaterai) ',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'docs_7',
                        'label' => 'Dokumen Kurikulum',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'docs_8',
                        'label' => 'Dokumen Rencana Induk Pengembangan (RIP) ',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'docs_9',
                        'label' => 'Daftar Calon Guru + CV + Ijazah terakhir',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'docs_10',
                        'label' => 'SK Pengangkatan Kepala Sekolah + CV + Ijazah terakhir',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'docs_11',
                        'label' => 'Daftar Calon Tenaga Kependidikan + CV + Ijazah terakhir',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'docs_12',
                        'label' => 'Daftar Sarana & Prasarana (detail list)',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'photo_5',
                        'label' => 'Foto Sarana & Prasarana (ruang kelas, fasilitas, dll)',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'photo_6',
                        'label' => 'Sertifikat / surat keterangan kepemilikan/hibah tanah/lahan',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'photo_7',
                        'label' => 'Dokumen Studi Kelayakan',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],

                ]
            ],
            [
                'title' => 'Mula Dhammasekha',
                'code' => 'mula-dhammasekha',
                'codex' => 'FL-MADMSK',
                'description' => 'Pendidikan keagamaan Buddha setingkat sekolah menengah pertama. Membutuhkan dokumen legalitas badan hukum, kurikulum, sarpras, dan SK pendirian.',
                'fields' => [

                ]
            ],
            [
                'title' => 'Muda Dammasekha',
                'code' => 'muda-dhammasekha',
                'codex' => 'FL-MDDMSK',
                'description' => 'Pendidikan keagamaan Buddha setingkat sekolah menengah atas. Persyaratan meliputi akta notaris, kurikulum, SK pengurus, serta daftar pendidik dan tenaga kependidikan.',
                'fields' => [

                ]
            ],
            [
                'title' => 'Uttama Dhammasekha',
                'code' => 'uttama-dhammasekha',
                'codex' => 'FL-UTDMSK',
                'description' => 'Pendidikan keagamaan Buddha setingkat perguruan tinggi. Dokumen yang diminta mencakup akta notaris, kurikulum, sarpras, SK kepala, hingga rencana induk pengembangan.',
                'fields' => [

                ]
            ],
        ],
        'nonformal' => [
            [
                'title' => 'Pasastrian',
                'code' => 'pasastrian',
                'codex' => 'NF-PSSTRN',
                'description' => 'Pendidikan nonformal berbasis asrama dengan syarat dokumen strategis: rencana pengembangan, kalender pendidikan, data siswa & pendidik, serta surat kesanggupan biaya 3 tahun.',
                'fields' => []
            ],
            [
                'title' => 'Sekolah Minggu Buddha',
                'code' => 'sekolah-minggu-buddha',
                'codex' => 'NF-SMBDDH',
                'description' => 'Pendidikan nonformal untuk anak-anak dan remaja. Persyaratan sederhana berupa SK pengurus, rencana program pendidikan, data peserta, data pendidik, serta surat domisili yayasan.',
                'fields' => []
            ],
            [
                'title' => 'Sikkaphana',
                'code' => 'sikkaphana',
                'codex' => 'NF-SKKPHN',
                'description' => 'Pendidikan nonformal bagi komunitas dan masyarakat umum. Dokumen wajib meliputi SK pengurus, rencana strategis, kalender kegiatan, data siswa & tenaga pendidik, serta surat pernyataan keabsahan dokumen.',
                'fields' => []
            ],
        ],
    ],
    'file_section' => [
        'dokumen-penyelenggara',
        'sarana-&-Foto',
        'dokumen'
    ],
    'file_aliases' =>[
        'docs_1' => 'Tanda Daftar Yayasan/Perkumpulan dari Kementerian Agama',
        'docs_2' => 'AD/ART *',
        'docs_3' => 'Upload Foto Rekening',
        'photo_1' => 'Foto Sarpras',
        'photo_2' => 'Foto Gedung Depan',
        'photo_3' => 'Foto Gedung Samping',
        'photo_4' => 'Tambahan Foto Sarpras (Opsional)',

        'docs_4' => 'SK Pengurus Organisasi (struktur & susunan + KTP)',
        'docs_5' => 'SK Struktur Manajemen & Personalia Penyelenggara Pendidikan',
        'docs_6' => 'Surat Pernyataan Kesanggupan Pembiayaan min. 1 tahun (bermaterai) ',
        'docs_7' => 'Dokumen Kurikulum',
        'docs_8' => 'Dokumen Rencana Induk Pengembangan (RIP)',
        'docs_9' => 'Daftar Calon Guru + CV + Ijazah terakhir',
        'docs_10' => 'SK Pengangkatan Kepala Sekolah + CV + Ijazah terakhir',
        'docs_11' => 'Daftar Calon Tenaga Kependidikan + CV + Ijazah terakhir',
        'docs_12' => 'Daftar Sarana & Prasarana (detail list)',

        'photo_5' => 'Foto Sarana & Prasarana (ruang kelas, fasilitas, dll)',
        'photo_6' => 'Sertifikat / surat keterangan kepemilikan/hibah tanah/lahan',
        'photo_7' => 'Dokumen Studi Kelayakan',
    ]
];