<?php

return [
    'form_type' => [
        'formal' => [
            [
                'title' => 'Nava Dhammasekha',
                'code' => 'nava-dhammasekha',
                'file_count' => 0, 
                'description' => 'Pendidikan dasar keagamaan Buddha setingkat sekolah dasar. Persyaratan lengkap mencakup akta notaris, kurikulum, daftar guru, hingga studi kelayakan.',
                'fields' => [
                    [
                        'type' => 'text',
                        'name' => 'pic_name',
                        'label' => 'Nama Penanggung Jawab',
                        'placeholder' => 'Input nama penanggung jawab',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'identitas-lembaga',
                        'group' => 1,
                    ],
                    [
                        'type' => 'text',
                        'name' => 'edu_organization_name',
                        'label' => 'Nama Lembaga Pendidikan',
                        'placeholder' => 'Masukkan nama lembaga pendidikan',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'identitas-lembaga',
                        'group' => 1,
                    ],
                     [
                        'type' => 'text',
                        'name' => 'edu_organization_chief',
                        'label' => 'Nama Kepala Lembaga',
                        'placeholder' => 'Masukkan nama kepala lembaga pendidikan',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'identitas-lembaga',
                        'group' => 1,
                    ],

                    [
                        'type' => 'text',
                        'name' => 'organization_name',
                        'label' => 'Nama Badan Penyelenggara',
                        'placeholder' => 'Masukkan nama badan penyelenggara',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'identitas-lembaga',
                        'group' => 2,
                    ],
                    
                    [
                        'type' => 'text',
                        'name' => 'edu_organization_phone',
                        'label' => 'Nomor Telepon Lembaga',
                        'placeholder' => 'Masukkan nomor telpon lembaga pendidikan',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'identitas-lembaga',
                        'group' => 2,
                    ],
                    [
                        'type' => 'date',
                        'name' => 'established_date',
                        'label' => 'Tanggal Berdiri',
                        'placeholder' => 'Pilih tanggal',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'identitas-lembaga',
                        'group' => 2,
                    ],
                    // dok
                    [
                        'type' => 'file',
                        'name' => 'file_1',
                        'label' => 'Tanda Daftar Yayasan/Perkumpulan dari Kementerian Agama',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'dokumen-penyelenggara',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_2',
                        'label' => 'AD/ART ',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'dokumen-penyelenggara',
                    ],

                    // Alamat Lembaga Pendidikan
                    [
                        'type' => 'select',
                        'name' => 'province',
                        'label' => 'Provinsi',
                        'placeholder' => 'Pilih Provinsi',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'alamat-lembaga-pendidikan',
                        'group' => 1,
                        'options' => [
                            'Banten',
                            'DKI Jakarta',
                        ]
                    ],
                    [
                        'type' => 'select',
                        'name' => 'city',
                        'label' => 'Kabupaten',
                        'placeholder' => 'Pilih Kabupaten',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'alamat-lembaga-pendidikan',
                        'group' => 2,
                        'options' => [
                            'Tangerang',
                            'Serang',
                        ]
                    ],
                    [
                        'type' => 'select',
                        'name' => 'district',
                        'label' => 'Kabupaten',
                        'placeholder' => 'Pilih Kabupaten',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'alamat-lembaga-pendidikan',
                        'group' => 1,
                        'options' => [
                            'Tangerang',
                            'Serang',
                        ]
                    ],
                    [
                        'type' => 'select',
                        'name' => 'subdistrict',
                        'label' => 'Kecamatan',
                        'placeholder' => 'Pilih Kecamatan',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'alamat-lembaga-pendidikan',
                        'group' => 2,
                        'options' => [
                            'Tangerang',
                            'Serang',
                        ]
                    ],
                    [
                        'type' => 'textarea',
                        'name' => 'address',
                        'label' => 'Alamat Lengkap',
                        'placeholder' => 'Masukkan alamat lembaga',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'alamat-lembaga-pendidikan',
                        'group' => 1
                    ],
                    // Sarana & Foto
                    [
                        'type' => 'file',
                        'name' => 'file_3',
                        'label' => 'Foto Sarpras',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'sarana-&-Foto',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_4',
                        'label' => 'Foto Gedung Depan',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'sarana-&-Foto',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_5',
                        'label' => 'Foto Gedung Samping',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'sarana-&-Foto',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_6',
                        'label' => 'Tambahan Foto Sarpras',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'sarana-&-Foto',
                    ],

                    // Rekening
                    [
                        'type' => 'select',
                        'name' => 'bank_name',
                        'label' => 'Pilih Bank',
                        'placeholder' => 'Pilih Bank',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'rekening',
                        'group' => 1,
                        'options' => [
                            'BCA',
                            'Mandiri',
                        ]
                    ],
                    [
                        'type' => 'text',
                        'name' => 'account_name',
                        'label' => 'Nomor Rekening',
                        'placeholder' => 'Nomor Rekening',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'rekening',
                        'group' => 1,
                    ],
                    [
                        'type' => 'text',
                        'name' => 'bank_office',
                        'label' => 'Cabang Bank',
                        'placeholder' => 'Cabang Bank',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'rekening',
                        'group' => 1,
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_7',
                        'label' => 'Upload Foto Rekening',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 1,
                        'section' => 'rekening',
                    ],
                    // PAGE 2
                    [
                        'type' => 'file',
                        'name' => 'file_8',
                        'label' => 'SK Pengurus Organisasi (struktur & susunan + KTP)',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_9',
                        'label' => 'SK Struktur Manajemen & Personalia Penyelenggara Pendidikan',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_10',
                        'label' => 'Surat Pernyataan Kesanggupan Pembiayaan min. 1 tahun (bermaterai) ',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_11',
                        'label' => 'Dokumen Kurikulum',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_12',
                        'label' => 'Dokumen Rencana Induk Pengembangan (RIP) ',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_13',
                        'label' => 'Daftar Calon Guru + CV + Ijazah terakhir',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_14',
                        'label' => 'SK Pengangkatan Kepala Sekolah + CV + Ijazah terakhir',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_15',
                        'label' => 'Daftar Calon Tenaga Kependidikan + CV + Ijazah terakhir',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_16',
                        'label' => 'Daftar Sarana & Prasarana (detail list)',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_17',
                        'label' => 'Foto Sarana & Prasarana (ruang kelas, fasilitas, dll)',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_18',
                        'label' => 'Sertifikat / surat keterangan kepemilikan/hibah tanah/lahan',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],
                    [
                        'type' => 'file',
                        'name' => 'file_19',
                        'label' => 'Dokumen Studi Kelayakan',
                        'placeholder' => 'file (pdf,jpg,png) maks 2 MB',
                        'required' => true,
                        'active' => true,
                        'page' => 2,
                        'section' => 'dokumen',
                    ],

                ]
            ],
            [
                'title' => 'Mula Dhammasekha',
                'code' => 'mula-dhammasekha',
                'description' => 'Pendidikan keagamaan Buddha setingkat sekolah menengah pertama. Membutuhkan dokumen legalitas badan hukum, kurikulum, sarpras, dan SK pendirian.',
                'fields' => [

                ]
            ],
            [
                'title' => 'Muda Dammasekha',
                'code' => 'muda-dhammasekha',
                'description' => 'Pendidikan keagamaan Buddha setingkat sekolah menengah atas. Persyaratan meliputi akta notaris, kurikulum, SK pengurus, serta daftar pendidik dan tenaga kependidikan.',
                'fields' => [

                ]
            ],
            [
                'title' => 'Uttama Dhammasekha',
                'code' => 'uttama-dhammasekha',
                'description' => 'Pendidikan keagamaan Buddha setingkat perguruan tinggi. Dokumen yang diminta mencakup akta notaris, kurikulum, sarpras, SK kepala, hingga rencana induk pengembangan.',
                'fields' => [

                ]
            ],
        ],
        'nonformal' => [
            [
                'title' => 'Pasastrian',
                'code' => 'pasastrian',
                'description' => 'Pendidikan nonformal berbasis asrama dengan syarat dokumen strategis: rencana pengembangan, kalender pendidikan, data siswa & pendidik, serta surat kesanggupan biaya 3 tahun.',
                'fields' => []
            ],
            [
                'title' => 'Sekolah Minggu Buddha',
                'code' => 'sekolah-minggu-buddha',
                'description' => 'Pendidikan nonformal untuk anak-anak dan remaja. Persyaratan sederhana berupa SK pengurus, rencana program pendidikan, data peserta, data pendidik, serta surat domisili yayasan.',
                'fields' => []
            ],
            [
                'title' => 'Sikkaphana',
                'code' => 'sikkaphana',
                'description' => 'Pendidikan nonformal bagi komunitas dan masyarakat umum. Dokumen wajib meliputi SK pengurus, rencana strategis, kalender kegiatan, data siswa & tenaga pendidik, serta surat pernyataan keabsahan dokumen.',
                'fields' => []
            ],
        ],
    ],
    'file_section' => [
        'dokumen-penyelenggara',
        'sarana-&-Foto'
    ]
];